[theme]

# Primary accent for interactive elements
primaryColor = '#0e47a1'

# Background color for the main content area
backgroundColor = '#7e9bca'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#03a9f5'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
